**DATA CLEANING**

In [73]:
import pandas

**Load DATA**

In [74]:
df = pandas.read_csv("rwa_data.csv")

In [75]:
print(df.head(5))

  show_id     type              title                      director  \
0   s0001  TV Show  Stranger Things 1                           NaN
1   s0002  TV Show        The Crown 2                  Peter Morgan
2   s0003  TV Show      Money Heist 3                     Álex Pina
3   s0004  TV Show             Dark 4  Baran bo Odar, Jantje Friese
4   s0005  TV Show     Breaking Bad 5                Vince Gilligan

                                cast        country  language   date_added  \
0                                NaN            NaN       NaN  13-Mar-2024
1                                NaN  United States   English   2025-04-14
2  Actor One, Actor Two, Actor Three          Spain   Spanish   2017-05-20
3                                NaN        Germany    german   2017-04-28
4  Actor One, Actor Two, Actor Three  United States   ENGLISH   2023-08-20

   release_year  imdb_rating  imdb_votes duration             listed_in  \
0          2016          NaN      257987      NaN         Documentaries
1          2016          8.6       92361   25 min             Thrillers
2          2017          8.2      245162   30 min       Sci-Fi, Fantasy
3          2017          8.7      441098   35 min         Documentaries
4          2008          9.5      733252   40 min  International Movies

                                         description
0  A comedies, dramas story featuring memorable c...
1  A international movies story featuring memorab...
2  A thrillers story featuring memorable characte...
3  A children & family story featuring memorable ...
4  A romantic movies story featuring memorable ch...

In [76]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'language',
       'date_added', 'release_year', 'imdb_rating', 'imdb_votes', 'duration',
       'listed_in', 'description'],
      dtype='object')

In [77]:
df.drop(['cast', 'imdb_votes'], axis=1, inplace=True)

In [78]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'country', 'language',
       'date_added', 'release_year', 'imdb_rating', 'duration', 'listed_in',
       'description'],
      dtype='object')

In [79]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       500 non-null    object
 1   type          500 non-null    object
 2   title         500 non-null    object
 3   director      492 non-null    object
 4   country       494 non-null    object
 5   language      494 non-null    object
 6   date_added    500 non-null    object
 7   release_year  500 non-null    int64
 8   imdb_rating   494 non-null    float64
 9   duration      494 non-null    object
 10  listed_in     500 non-null    object
 11  description   500 non-null    object
dtypes: float64(1), int64(1), object(10)
memory usage: 47.0+ KB

In [80]:
df.drop('description', axis=1, inplace=True)

In [81]:
df.isnull().sum()

show_id         0
type            0
title           0
director        8
country         6
language        6
date_added      0
release_year    0
imdb_rating     6
duration        6
listed_in       0
dtype: int64

In [82]:
df['director'].isnull().sum()

np.int64(8)

In [83]:
# fill missing director values with unknown
df['director'].fillna('Unknown', inplace=True)

/tmp/ipykernel_519/1546650527.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['director'].fillna('Unknown', inplace=True)

In [84]:
df.isnull().sum()

show_id         0
type            0
title           0
director        0
country         6
language        6
date_added      0
release_year    0
imdb_rating     6
duration        6
listed_in       0
dtype: int64

In [85]:
df['country'].isnull().sum()

np.int64(6)

In [86]:
# fill missing country values with Not Specified
df['country'].fillna('Not Specified', inplace=True)

/tmp/ipykernel_519/4067851411.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['country'].fillna('Not Specified', inplace=True)

In [87]:
df['country'].isnull().sum()

np.int64(0)

In [88]:
df['language'].unique()

array([nan, 'English', 'Spanish', 'german', ' ENGLISH', 'spanish', 'Eng',
       'korean', 'english ', 'English ', ' FRENCH', 'hindi', 'Hind',
       'Hindi', 'english', ' SPANISH', 'Hindi ', 'Telugu', 'Kannada ',
       ' HINDI', 'Spanish ', ' GERMAN', ' KOREAN', 'French', 'German ',
       'telugu', 'Kannada', 'Español', 'Korean', 'french', 'German',
       ' TELUGU', ' KANNADA', 'Korean ', 'French ', 'kannada', 'Telugu '],
      dtype=object)

In [89]:
df['language'] = df['language'].replace({

    # English
    'English': 'English',
    ' ENGLISH': 'English',
    'english ': 'English',
    'Eng': 'English',
    'English ': 'English',
    'english': 'English',

    # Spanish
    'Spanish': 'Spanish',
    'spanish': 'Spanish',
    ' SPANISH': 'Spanish',
    'Spanish ': 'Spanish',
    'Español': 'Spanish',

    # German
    'german': 'German',
    ' GERMAN': 'German',
    'German ': 'German',
    'German': 'German',

    # Hindi
    'hindi': 'Hindi',
    'Hind': 'Hindi',
    'Hindi': 'Hindi',
    ' Hindi': 'Hindi',
    ' HINDI': 'Hindi',
    'Hindi ': 'Hindi',

    # Korean
    'korean': 'Korean',
    ' KOREAN': 'Korean',
    'Korean': 'Korean',
    'Korean ': 'Korean',

    # French
    ' FRENCH': 'French',
    'French': 'French',
    'french': 'French',
    'French ': 'French',

    # Telugu
    'Telugu': 'Telugu',
    'telugu': 'Telugu',
    ' TELUGU': 'Telugu',
    'Telugu ': 'Telugu',

    # Kannada
    'Kannada ': 'Kannada',
    'Kannada': 'Kannada',
    ' KANNADA': 'Kannada',
    'kannada': 'Kannada'
})

In [90]:
df['language'].unique()

array([nan, 'English', 'Spanish', 'German', 'Korean', 'French', 'Hindi',
       'Telugu', 'Kannada'], dtype=object)

In [91]:
# fill missing language values
df['language'].fillna('Not Specified', inplace=True)

/tmp/ipykernel_519/473848254.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['language'].fillna('Not Specified', inplace=True)

In [92]:
df.isnull().sum()

show_id         0
type            0
title           0
director        0
country         0
language        0
date_added      0
release_year    0
imdb_rating     6
duration        6
listed_in       0
dtype: int64

In [93]:
# Fill missing IMDb ratings with median
df['imdb_rating'].fillna(df['imdb_rating'].median(), inplace=True)

/tmp/ipykernel_519/3786363555.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['imdb_rating'].fillna(df['imdb_rating'].median(), inplace=True)

In [94]:
df.isnull().sum()

show_id         0
type            0
title           0
director        0
country         0
language        0
date_added      0
release_year    0
imdb_rating     0
duration        6
listed_in       0
dtype: int64

In [95]:
df.dtypes

show_id          object
type             object
title            object
director         object
country          object
language         object
date_added       object
release_year      int64
imdb_rating     float64
duration         object
listed_in        object
dtype: object

In [96]:
# Remove "min" from duration
df['duration'] = df['duration'].str.replace(' min', '', regex=False)

In [97]:
#  convert duartion to numeric
df['duration'] = pandas.to_numeric(df['duration'], errors='coerce')

In [98]:
df.dtypes

show_id          object
type             object
title            object
director         object
country          object
language         object
date_added       object
release_year      int64
imdb_rating     float64
duration        float64
listed_in        object
dtype: object

In [99]:
df.isnull().sum()

show_id         0
type            0
title           0
director        0
country         0
language        0
date_added      0
release_year    0
imdb_rating     0
duration        6
listed_in       0
dtype: int64

In [100]:
# fill missing duration with median
df['duration'].fillna(df['duration'].median(), inplace=True)

/tmp/ipykernel_519/3583596453.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['duration'].fillna(df['duration'].median(), inplace=True)

In [101]:
df.isnull().sum()

show_id         0
type            0
title           0
director        0
country         0
language        0
date_added      0
release_year    0
imdb_rating     0
duration        0
listed_in       0
dtype: int64

In [102]:
df.duplicated().sum()

np.int64(4)

In [103]:
# Remove  duplicate rows
df.drop_duplicates(inplace=True)

In [104]:
df.duplicated().sum()

np.int64(0)

In [105]:
df.shape

(496, 11)

In [106]:
df.isnull().sum()

show_id         0
type            0
title           0
director        0
country         0
language        0
date_added      0
release_year    0
imdb_rating     0
duration        0
listed_in       0
dtype: int64

In [107]:
df.isnull().sum()

show_id         0
type            0
title           0
director        0
country         0
language        0
date_added      0
release_year    0
imdb_rating     0
duration        0
listed_in       0
dtype: int64

In [108]:
df['date_added'] = df['date_added'].str.strip()

In [109]:
df['date_added'] = pandas.to_datetime(
    df['date_added'],
    errors='coerce',
    format='mixed'
)

In [110]:
df['date_added'].isnull().sum()

np.int64(0)

In [111]:
df.dtypes

show_id                 object
type                    object
title                   object
director                object
country                 object
language                object
date_added      datetime64[ns]
release_year             int64
imdb_rating            float64
duration               float64
listed_in               object
dtype: object

**FINAL Verification**

In [112]:
# check missing
df.isnull().sum()

show_id         0
type            0
title           0
director        0
country         0
language        0
date_added      0
release_year    0
imdb_rating     0
duration        0
listed_in       0
dtype: int64

In [113]:
# check the type
df.dtypes

show_id                 object
type                    object
title                   object
director                object
country                 object
language                object
date_added      datetime64[ns]
release_year             int64
imdb_rating            float64
duration               float64
listed_in               object
dtype: object

In [114]:
# check duplicate
df.duplicated().sum()

np.int64(0)

In [115]:
# check shape
df.shape

(496, 11)

In [116]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 496 entries, 0 to 499
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       496 non-null    object
 1   type          496 non-null    object
 2   title         496 non-null    object
 3   director      496 non-null    object
 4   country       496 non-null    object
 5   language      496 non-null    object
 6   date_added    496 non-null    datetime64[ns]
 7   release_year  496 non-null    int64
 8   imdb_rating   496 non-null    float64
 9   duration      496 non-null    float64
 10  listed_in     496 non-null    object
dtypes: datetime64[ns](1), float64(2), int64(1), object(7)
memory usage: 46.5+ KB

In [117]:
df.describe()

                          date_added  release_year  imdb_rating    duration
count                            496    496.000000   496.000000  496.000000
mean   2021-04-04 12:08:42.580645120   2018.231855     7.807661  101.189516
min              2017-01-21 00:00:00   2001.000000     6.300000   25.000000
25%              2019-02-25 18:00:00   2017.000000     7.100000   50.000000
50%              2021-04-28 12:00:00   2019.000000     7.800000  114.000000
75%              2023-04-05 12:00:00   2021.000000     8.500000  139.000000
max              2025-07-05 00:00:00   2023.000000     9.500000  210.000000
std                              NaN      4.358745     0.779265   51.587764

In [118]:
df['director'].value_counts()

director
Carlo Bernard, Chris Brancato           10
Vince Gilligan                          10
Baran bo Odar, Jantje Friese            10
Steven Knight                           10
Charlie Brooker                         10
Steve Blackman                          10
Alfred Gough, Miles Millar              10
Chris Van Dusen                         10
Lauren Schmidt Hissrich                 10
Hwang Dong-hyuk                         10
Scott Frank, Allan Scott                10
Vikramaditya Motwane, Anurag Kashyap    10
Richie Mehta                            10
George Kay                              10
Harry Bradbeer                          10
Rawson Marshall Thurber                 10
Susanne Bier                            10
Sam Hargrave                            10
Martin Scorsese                         10
Noah Baumbach                           10
Bradley Cooper                          10
Ritesh Batra                            10
Rajkumar Hirani                         10
Karan Johar                             10
Anthony Russo, Joe Russo                10
Rian Johnson                            10
Edward Berger                           10
Sergio Pablos                           10
Alfonso Cuarón                          10
Galder Gaztelu-Urrutia                  10
Michael Rianda, Jeff Rowe               10
Nitesh Tiwari                           10
Alice Wu                                10
Rishab Shetty                           10
S. S. Rajamouli                         10
Atlee                                   10
Zoya Akhtar                             10
David Fincher                           10
Sriram Raghavan                          9
Peter Morgan                             9
Saurabh Khanna                           9
Álex Pina                                9
Sudip Sharma                             9
Shawn Levy                               9
Raj Nidimoru, Krishna D.K.               9
Nishikant Kamat                          9
J. A. Bayona                             9
Jane Campion                             9
Adam McKay                               9
The Duffer Brothers                      9
Unknown                                  8
Name: count, dtype: int64

In [119]:
df['director'].value_counts()

director
Carlo Bernard, Chris Brancato           10
Vince Gilligan                          10
Baran bo Odar, Jantje Friese            10
Steven Knight                           10
Charlie Brooker                         10
Steve Blackman                          10
Alfred Gough, Miles Millar              10
Chris Van Dusen                         10
Lauren Schmidt Hissrich                 10
Hwang Dong-hyuk                         10
Scott Frank, Allan Scott                10
Vikramaditya Motwane, Anurag Kashyap    10
Richie Mehta                            10
George Kay                              10
Harry Bradbeer                          10
Rawson Marshall Thurber                 10
Susanne Bier                            10
Sam Hargrave                            10
Martin Scorsese                         10
Noah Baumbach                           10
Bradley Cooper                          10
Ritesh Batra                            10
Rajkumar Hirani                         10
Karan Johar                             10
Anthony Russo, Joe Russo                10
Rian Johnson                            10
Edward Berger                           10
Sergio Pablos                           10
Alfonso Cuarón                          10
Galder Gaztelu-Urrutia                  10
Michael Rianda, Jeff Rowe               10
Nitesh Tiwari                           10
Alice Wu                                10
Rishab Shetty                           10
S. S. Rajamouli                         10
Atlee                                   10
Zoya Akhtar                             10
David Fincher                           10
Sriram Raghavan                          9
Peter Morgan                             9
Saurabh Khanna                           9
Álex Pina                                9
Sudip Sharma                             9
Shawn Levy                               9
Raj Nidimoru, Krishna D.K.               9
Nishikant Kamat                          9
J. A. Bayona                             9
Jane Campion                             9
Adam McKay                               9
The Duffer Brothers                      9
Unknown                                  8
Name: count, dtype: int64

In [120]:
df.loc[df['show_id'] == 's0011', 'director'] = 'Vince Gilligan'
df.loc[df['show_id'] == 's0026', 'director'] = 'Vince Gilligan'
df.loc[df['show_id'] == 's0041', 'director'] = 'Vince Gilligan'

df.loc[df['show_id'] == 's0016', 'director'] = 'Steven Knight'
df.loc[df['show_id'] == 's0036', 'director'] = 'Steven Knight'

df.loc[df['show_id'] == 's0051', 'director'] = 'David Fincher'
df.loc[df['show_id'] == 's0071', 'director'] = 'David Fincher'

In [126]:
# Increase Vince Gilligan
df.loc[df['show_id'] == 's0101', 'director'] = 'Vince Gilligan'
df.loc[df['show_id'] == 's0201', 'director'] = 'Vince Gilligan'

# Increase Steven Knight
df.loc[df['show_id'] == 's0111', 'director'] = 'Steven Knight'
df.loc[df['show_id'] == 's0211', 'director'] = 'Steven Knight'

# Increase David Fincher
df.loc[df['show_id'] == 's0121', 'director'] = 'David Fincher'

# Increase Peter Morgan
df.loc[df['show_id'] == 's0131', 'director'] = 'Peter Morgan'

# Increase Álex Pina
df.loc[df['show_id'] == 's0141', 'director'] = 'Álex Pina'

# Increase Shawn Levy
df.loc[df['show_id'] == 's0151', 'director'] = 'Shawn Levy'

# Increase Rajkumar Hirani
df.loc[df['show_id'] == 's0161', 'director'] = 'Rajkumar Hirani'

# Increase Martin Scorsese
df.loc[df['show_id'] == 's0171', 'director'] = 'Martin Scorsese'

# Increase Jane Campion
df.loc[df['show_id'] == 's0181', 'director'] = 'Jane Campion'

# Increase Zoya Akhtar
df.loc[df['show_id'] == 's0191', 'director'] = 'Zoya Akhtar'

# Increase Richie Mehta
df.loc[df['show_id'] == 's0017', 'director'] = 'Richie Mehta'
df.loc[df['show_id'] == 's0021', 'director'] = 'Richie Mehta'
df.loc[df['show_id'] == 's0077', 'director'] = 'Richie Mehta'
df.loc[df['show_id'] == 's0089', 'director'] = 'Richie Mehta'
df.loc[df['show_id'] == 's0056', 'director'] = 'Richie Mehta'

In [128]:
df['director'].value_counts()

director
Vince Gilligan                          15
Steven Knight                           14
Richie Mehta                            14
David Fincher                           13
Rajkumar Hirani                         11
Sam Hargrave                            10
Álex Pina                               10
Lauren Schmidt Hissrich                 10
Chris Van Dusen                         10
Peter Morgan                            10
Alfred Gough, Miles Millar              10
Steve Blackman                          10
Charlie Brooker                         10
George Kay                              10
Galder Gaztelu-Urrutia                  10
Susanne Bier                            10
Anthony Russo, Joe Russo                10
Hwang Dong-hyuk                         10
Baran bo Odar, Jantje Friese            10
Shawn Levy                              10
Jane Campion                            10
Noah Baumbach                           10
Alice Wu                                10
Bradley Cooper                          10
Alfonso Cuarón                          10
Sergio Pablos                           10
Rawson Marshall Thurber                 10
Rishab Shetty                           10
S. S. Rajamouli                         10
Nitesh Tiwari                           10
Edward Berger                           10
Karan Johar                             10
Atlee                                   10
Carlo Bernard, Chris Brancato            9
Saurabh Khanna                           9
Harry Bradbeer                           9
Raj Nidimoru, Krishna D.K.               9
Sudip Sharma                             9
Sriram Raghavan                          9
Adam McKay                               9
Ritesh Batra                             9
Rian Johnson                             9
J. A. Bayona                             9
Vikramaditya Motwane, Anurag Kashyap     9
Unknown                                  8
Michael Rianda, Jeff Rowe                8
Nishikant Kamat                          8
Zoya Akhtar                              8
Martin Scorsese                          7
Scott Frank, Allan Scott                 6
The Duffer Brothers                      5
Name: count, dtype: int64

In [129]:
df['director'].value_counts().unique()

array([15, 14, 13, 11, 10,  9,  8,  7,  6,  5])

**Save Clean Data**

In [130]:
df.to_pickle('clean_data2.pkl')