In [15]:
import pandas
import numpy

In [16]:
df = pandas.read_csv("it_job_apps (2).csv")

In [17]:
print(df.head())

  Application_ID Candidate_Name  Gender  Age       City        State  \
0        APP0001    Anya Butala    Male   27  Ahmedabad      Gujarat
1        APP0002      Hansh Bal  Female   24    Gurgaon      Haryana
2        APP0003   Ahana  Yadav    Male   30       Pune  Maharashtra
3        APP0004      Urvi Bora  Female   38    Chennai   Tamil Nadu
4        APP0005  Alisha Mammen  Female   34  Hyderabad    Telangana

  Qualification        Specialization                       College_Name  \
0          B.E.      Computer Science  Dayal, Walia and Gandhi Institute
1        B.Tech  Software Engineering              Cherian PLC Institute
2        B.Tech          Data Science   Wagle, Barad and Samra Institute
3          B.E.       Cloud Computing        Banerjee and Sons Institute
4           BCA  Software Engineering            Sanghvi Group Institute

   Graduation_Year  ...  Expected_Salary_LPA Current_Salary_LPA  \
0             2024  ...                 12.5                NaN
1             2024  ...                 22.3               18.1
2             2021  ...                 34.2               31.7
3             2023  ...                 10.5                8.4
4             2023  ...                 31.2               28.9

  Notice_Period_Days Application_Date Interview_Score Technical_Test_Score  \
0                 30       2025-01-16            74.0                 66.0
1                 45       2025-04-21            60.0                  NaN
2                 45       2025-12-05             NaN                 83.0
3                 30       2025-07-14            64.0                 94.0
4                 30       2025-05-07             NaN                 89.0

   Communication_Score    Status  Work_Mode Preferred_Location
0                 87.0   Pending     Onsite             Jaipur
1                 77.0   Pending     Hybrid             Indore
2                 64.0  Rejected     Onsite              Kochi
3                  NaN  Selected     Hybrid              Delhi
4                 76.0   Pending     Hybrid             Mumbai

[5 rows x 26 columns]

In [18]:
print(df.shape)

(505, 26)

In [19]:
print(df.columns)

Index(['Application_ID', 'Candidate_Name', 'Gender', 'Age', 'City', 'State',
       'Qualification', 'Specialization', 'College_Name', 'Graduation_Year',
       'Experience_Years', 'Previous_Company', 'Applied_Role', 'Department',
       'Skills', 'Certification', 'Expected_Salary_LPA', 'Current_Salary_LPA',
       'Notice_Period_Days', 'Application_Date', 'Interview_Score',
       'Technical_Test_Score', 'Communication_Score', 'Status', 'Work_Mode',
       'Preferred_Location'],
      dtype='object')

In [20]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 505 entries, 0 to 504
Data columns (total 26 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Application_ID        505 non-null    object
 1   Candidate_Name        505 non-null    object
 2   Gender                505 non-null    object
 3   Age                   505 non-null    int64
 4   City                  505 non-null    object
 5   State                 505 non-null    object
 6   Qualification         505 non-null    object
 7   Specialization        505 non-null    object
 8   College_Name          505 non-null    object
 9   Graduation_Year       505 non-null    int64
 10  Experience_Years      505 non-null    int64
 11  Previous_Company      354 non-null    object
 12  Applied_Role          505 non-null    object
 13  Department            505 non-null    object
 14  Skills                505 non-null    object
 15  Certification         387 non-null    object
 16  Expected_Salary_LPA   505 non-null    float64
 17  Current_Salary_LPA    387 non-null    float64
 18  Notice_Period_Days    505 non-null    int64
 19  Application_Date      505 non-null    object
 20  Interview_Score       235 non-null    float64
 21  Technical_Test_Score  231 non-null    float64
 22  Communication_Score   266 non-null    float64
 23  Status                505 non-null    object
 24  Work_Mode             505 non-null    object
 25  Preferred_Location    505 non-null    object
dtypes: float64(5), int64(4), object(17)
memory usage: 102.7+ KB
None

In [21]:
print(df.describe())

              Age  Graduation_Year  Experience_Years  Expected_Salary_LPA  \
count  505.000000       505.000000        505.000000           505.000000
mean    29.536634      2021.518812          3.558416            19.613465
std      5.290672         3.382985          3.247260             8.804169
min     21.000000      2014.000000          0.000000             4.000000
25%     25.000000      2019.000000          1.000000            11.900000
50%     29.000000      2022.000000          3.000000            19.700000
75%     35.000000      2024.000000          6.000000            27.000000
max     38.000000      2026.000000         10.000000            35.000000

       Current_Salary_LPA  Notice_Period_Days  Interview_Score  \
count          387.000000          505.000000       235.000000
mean            16.210078           49.396040        77.429787
std              8.792259           25.324904        10.215539
min             -0.900000           15.000000        60.000000
25%              8.400000           30.000000        68.000000
50%             16.000000           45.000000        77.000000
75%             23.950000           60.000000        86.000000
max             33.000000           90.000000        95.000000

       Technical_Test_Score  Communication_Score
count            231.000000           266.000000
mean              78.649351            76.992481
std               11.209196            10.578009
min               60.000000            60.000000
25%               68.000000            68.000000
50%               79.000000            77.000000
75%               89.000000            86.000000
max               98.000000            95.000000

**DATA CLEANING**

In [22]:
df.isnull().sum()

Application_ID            0
Candidate_Name            0
Gender                    0
Age                       0
City                      0
State                     0
Qualification             0
Specialization            0
College_Name              0
Graduation_Year           0
Experience_Years          0
Previous_Company        151
Applied_Role              0
Department                0
Skills                    0
Certification           118
Expected_Salary_LPA       0
Current_Salary_LPA      118
Notice_Period_Days        0
Application_Date          0
Interview_Score         270
Technical_Test_Score    274
Communication_Score     239
Status                    0
Work_Mode                 0
Preferred_Location        0
dtype: int64

In [23]:
print(df.isnull().sum().sum())  # Total Null values count

1170

In [24]:
print(df.isnull().sum()[df.isnull().sum() > 0] )

Previous_Company        151
Certification           118
Current_Salary_LPA      118
Interview_Score         270
Technical_Test_Score    274
Communication_Score     239
dtype: int64

In [25]:
df['Certification'] = df['Certification'].fillna('Not Certified')

In [26]:
print(df['Certification'].isnull().sum())

0

In [27]:
df['Current_Salary_LPA'] = df['Current_Salary_LPA'].fillna(0)

In [28]:
df['Interview_Score'] = df['Interview_Score'].fillna(df['Interview_Score'].mean())

In [29]:
df['Technical_Test_Score'] = df['Technical_Test_Score'].fillna(df['Technical_Test_Score'].mean())

In [30]:
print(df.isnull().sum()[df.isnull().sum() > 0])

Previous_Company       151
Communication_Score    239
dtype: int64

In [31]:
df['Communication_Score'] = df['Communication_Score'].fillna(df['Communication_Score'].mean())

In [32]:
print(df.isnull().sum()[df.isnull().sum() > 0])

Previous_Company    151
dtype: int64

In [33]:
# df['Previous_Company'] = df['Previous_Company'].replace("", "Fresher")

df['Previous_Company']  = df['Previous_Company'].fillna("Fresher")

In [34]:
print(df.isnull().sum()[df.isnull().sum() > 0])

Series([], dtype: int64)

In [35]:
df.isnull().sum()

Application_ID          0
Candidate_Name          0
Gender                  0
Age                     0
City                    0
State                   0
Qualification           0
Specialization          0
College_Name            0
Graduation_Year         0
Experience_Years        0
Previous_Company        0
Applied_Role            0
Department              0
Skills                  0
Certification           0
Expected_Salary_LPA     0
Current_Salary_LPA      0
Notice_Period_Days      0
Application_Date        0
Interview_Score         0
Technical_Test_Score    0
Communication_Score     0
Status                  0
Work_Mode               0
Preferred_Location      0
dtype: int64

**Check Duplicates**

In [36]:
print(df.duplicated().sum())

5

In [37]:
# Drop Duplicates rows
df = df.drop_duplicates()

In [38]:
print(df.duplicated().sum())

0

In [39]:
df.shape

(500, 26)

In [40]:
df.dtypes   # Application_date col is in Object

Application_ID           object
Candidate_Name           object
Gender                   object
Age                       int64
City                     object
State                    object
Qualification            object
Specialization           object
College_Name             object
Graduation_Year           int64
Experience_Years          int64
Previous_Company         object
Applied_Role             object
Department               object
Skills                   object
Certification            object
Expected_Salary_LPA     float64
Current_Salary_LPA      float64
Notice_Period_Days        int64
Application_Date         object
Interview_Score         float64
Technical_Test_Score    float64
Communication_Score     float64
Status                   object
Work_Mode                object
Preferred_Location       object
dtype: object

In [41]:
# convert the Application_date -> Object into -> dateformate
df['Application_Date'] = pandas.to_datetime(df['Application_Date'])

In [42]:
# check the datatypes
df.dtypes

Application_ID                  object
Candidate_Name                  object
Gender                          object
Age                              int64
City                            object
State                           object
Qualification                   object
Specialization                  object
College_Name                    object
Graduation_Year                  int64
Experience_Years                 int64
Previous_Company                object
Applied_Role                    object
Department                      object
Skills                          object
Certification                   object
Expected_Salary_LPA            float64
Current_Salary_LPA             float64
Notice_Period_Days               int64
Application_Date        datetime64[ns]
Interview_Score                float64
Technical_Test_Score           float64
Communication_Score            float64
Status                          object
Work_Mode                       object
Preferred_Location              object
dtype: object

**Handel String Function**

In [43]:
(df == "").sum()    # Check Empty String

Application_ID          0
Candidate_Name          0
Gender                  0
Age                     0
City                    0
State                   0
Qualification           0
Specialization          0
College_Name            0
Graduation_Year         0
Experience_Years        0
Previous_Company        0
Applied_Role            0
Department              0
Skills                  0
Certification           0
Expected_Salary_LPA     0
Current_Salary_LPA      0
Notice_Period_Days      0
Application_Date        0
Interview_Score         0
Technical_Test_Score    0
Communication_Score     0
Status                  0
Work_Mode               0
Preferred_Location      0
dtype: int64

In [44]:
df['Candidate_Name'] = df['Candidate_Name'].str.strip()

In [45]:
df['City'] = df['City'].str.strip()

In [46]:
df['Applied_Role'] = df['Applied_Role'].str.strip()

**DATA ANALYSIS**

In [47]:
print("Total Applications: ", len(df))

Total Applications:  500

In [48]:
selected = df[df['Status'] == 'Selected']

print("Selected Candidates: ", len(selected))

Selected Candidates:  160

In [49]:
selection_ratio = (
    len(selected) /len(df)
) * 100

print("Selection Ratio: ", selection_ratio)

Selection Ratio:  32.0

In [50]:
print(df['Applied_Role'].value_counts())

Applied_Role
Java Developer               40
Cyber Security Analyst       35
Data Analyst                 34
Business Analyst             33
Frontend Developer           32
Cloud Engineer               30
Machine Learning Engineer    29
DevOps Engineer              29
AI Engineer                  28
Data Scientist               28
Database Administrator       27
Python Developer             27
Backend Developer            26
QA Engineer                  24
BI Developer                 24
Full Stack Developer         20
Product Analyst              18
Project Manager              16
Name: count, dtype: int64

In [51]:
# Top Five Applied Roles
print(df['Applied_Role'].value_counts().head(5))

Applied_Role
Java Developer            40
Cyber Security Analyst    35
Data Analyst              34
Business Analyst          33
Frontend Developer        32
Name: count, dtype: int64

In [52]:
print(df['Expected_Salary_LPA'].mean())

19.587400000000002

In [53]:
print(round(df['Expected_Salary_LPA'].mean(), 2))

19.59

In [54]:
print(df['Expected_Salary_LPA'].max())

35.0

In [55]:
print(df['Expected_Salary_LPA'].describe())

count    500.000000
mean      19.587400
std        8.798068
min        4.000000
25%       11.900000
50%       19.650000
75%       27.025000
max       35.000000
Name: Expected_Salary_LPA, dtype: float64

In [56]:
# find How many Freshers Student
freshers = df[df['Experience_Years'] == 0]

print("Freshers: ", len(freshers))

Freshers:  117

In [57]:
# FInd the Exp People count
exp = df[df['Experience_Years'] != 0]

print("Exprenced Candidates: ", len(exp))

Exprenced Candidates:  383

In [58]:
# Gender Counts
gender_count =  df['Gender'].value_counts()

print(gender_count)

Gender
Male      267
Female    233
Name: count, dtype: int64

In [59]:
# Work mode counts
print(df['Work_Mode'].value_counts())

Work_Mode
Remote    168
Onsite    167
Hybrid    165
Name: count, dtype: int64

In [60]:
print(df['Preferred_Location'].value_counts())

Preferred_Location
Indore         49
Chennai        43
Ahmedabad      38
Kolkata        37
Bangalore      36
Delhi          36
Jaipur         36
Kochi          33
Mumbai         31
Hyderabad      30
Noida          29
Gurgaon        27
Pune           26
Nagpur         26
Bhubaneswar    23
Name: count, dtype: int64

In [61]:
print(df['State'].value_counts())

State
Maharashtra       98
Rajasthan         42
Delhi             38
West Bengal       37
Gujarat           35
Karnataka         34
Uttar Pradesh     34
Kerala            34
Odisha            33
Tamil Nadu        32
Haryana           30
Madhya Pradesh    29
Telangana         24
Name: count, dtype: int64

In [62]:
print(df['City'].value_counts())

City
Nagpur         42
Jaipur         42
Delhi          38
Kolkata        37
Ahmedabad      35
Kochi          34
Noida          34
Bangalore      34
Bhubaneswar    33
Chennai        32
Gurgaon        30
Indore         29
Mumbai         29
Pune           27
Hyderabad      24
Name: count, dtype: int64

In [63]:
salary_by_role = df.groupby(
    'Applied_Role'
)['Expected_Salary_LPA'].mean()

print(salary_by_role)

Applied_Role
AI Engineer                  19.782143
BI Developer                 18.454167
Backend Developer            19.426923
Business Analyst             21.257576
Cloud Engineer               17.706667
Cyber Security Analyst       18.200000
Data Analyst                 21.232353
Data Scientist               18.210714
Database Administrator       20.277778
DevOps Engineer              17.217241
Frontend Developer           22.071875
Full Stack Developer         21.330000
Java Developer               18.980000
Machine Learning Engineer    19.037931
Product Analyst              20.166667
Project Manager              21.750000
Python Developer             19.874074
QA Engineer                  18.820833
Name: Expected_Salary_LPA, dtype: float64

In [64]:
interview_by_role = df.groupby(
    'Applied_Role'
)['Interview_Score'].mean()

print(interview_by_role)

Applied_Role
AI Engineer                  77.638450
BI Developer                 76.780319
Backend Developer            76.440262
Business Analyst             80.217150
Cloud Engineer               78.400851
Cyber Security Analyst       75.359878
Data Analyst                 78.349312
Data Scientist               76.332371
Database Administrator       75.243972
DevOps Engineer              77.099193
Frontend Developer           79.969282
Full Stack Developer         75.714894
Java Developer               77.679362
Machine Learning Engineer    76.498166
Product Analyst              77.992671
Project Manager              77.714894
Python Developer             77.688416
QA Engineer                  77.554078
Name: Interview_Score, dtype: float64

In [65]:
print(df['Department'].value_counts())

Department
Software Development     93
Analytics                86
Cloud                    59
AI/ML                    57
Web Development          52
Security                 35
Business Intelligence    33
Database                 27
Testing                  24
Product                  18
Management               16
Name: count, dtype: int64

In [66]:
top_candidates = df.sort_values(
    by = 'Interview_Score',
    ascending= False
)

print(top_candidates)

    Application_ID     Candidate_Name  Gender  Age         City  \
87         APP0088        Azad Sangha    Male   37    Ahmedabad
254        APP0255     Manikya Sahota    Male   29    Bangalore
11         APP0012     Ryan Ahluwalia  Female   27  Bhubaneswar
285        APP0286       Advika Shere  Female   30      Kolkata
430        APP0431  Divyansh Varghese  Female   35        Noida
..             ...                ...     ...  ...          ...
400        APP0401      Kartik Chanda    Male   38         Pune
446        APP0447        Samar Garde  Female   36       Mumbai
216        APP0217          Zara Mani  Female   27        Delhi
156        APP0157    Mohanlal Mammen    Male   29    Bangalore
1          APP0002          Hansh Bal  Female   24      Gurgaon

             State      Qualification          Specialization  \
87         Gujarat               B.E.          Cyber Security
254      Karnataka                MCA            Data Science
11          Odisha  M.Sc Data Science    Software Engineering
285    West Bengal                MBA      Business Analytics
430  Uttar Pradesh             B.Tech        Computer Science
..             ...                ...                     ...
400    Maharashtra             B.Tech      Business Analytics
446    Maharashtra             M.Tech         Cloud Computing
216          Delhi               B.E.                 AI & ML
156      Karnataka  M.Sc Data Science  Information Technology
1          Haryana             B.Tech    Software Engineering

                            College_Name  Graduation_Year  ...  \
87                 Arora-Hayre Institute             2021  ...
254    Srinivas, Gour and Dutt Institute             2024  ...
11                Dass-Sanghvi Institute             2020  ...
285  Khalsa, Sodhi and Khurana Institute             2019  ...
430                  Kanda Ltd Institute             2026  ...
..                                   ...              ...  ...
400                   Bora PLC Institute             2019  ...
446              Mani and Sons Institute             2025  ...
216              Sani and Sons Institute             2023  ...
156           Dube-Viswanathan Institute             2022  ...
1                  Cherian PLC Institute             2024  ...

     Expected_Salary_LPA Current_Salary_LPA Notice_Period_Days  \
87                  25.1               22.7                 45
254                 29.5                0.0                 45
11                   7.0                3.4                 60
285                 13.7                9.4                 30
430                 26.1                0.0                 60
..                   ...                ...                ...
400                 22.9               21.9                 45
446                 27.3                0.0                 60
216                 28.6               24.1                 90
156                 28.9               27.3                 30
1                   22.3               18.1                 45

    Application_Date Interview_Score Technical_Test_Score  \
87        2026-03-02            95.0            78.649351
254       2025-03-21            95.0            66.000000
11        2025-09-06            94.0            65.000000
285       2025-02-19            94.0            89.000000
430       2025-07-19            94.0            88.000000
..               ...             ...                  ...
400       2026-02-08            60.0            78.649351
446       2025-07-12            60.0            66.000000
216       2025-09-21            60.0            88.000000
156       2025-07-10            60.0            74.000000
1         2025-04-21            60.0            78.649351

     Communication_Score    Status  Work_Mode Preferred_Location
87             92.000000   Pending     Remote            Chennai
254            76.992481  Rejected     Remote            Kolkata
11             76.992481  Selected     Hybrid          Hyderabad
285            76.992481  Selected     Onsite          Hyderabad
430            93.000000  Selected     Remote            Chennai
..                   ...       ...        ...                ...
400            85.000000  Rejected     Onsite            Chennai
446            93.000000  Rejected     Hybrid          Ahmedabad
216            74.000000   Pending     Remote          Ahmedabad
156            76.992481   Pending     Hybrid             Indore
1              77.000000   Pending     Hybrid             Indore

[500 rows x 26 columns]

In [67]:
interview_by_role = df.groupby(
    'Applied_Role'
)['Interview_Score'].mean()

print(interview_by_role)

Applied_Role
AI Engineer                  77.638450
BI Developer                 76.780319
Backend Developer            76.440262
Business Analyst             80.217150
Cloud Engineer               78.400851
Cyber Security Analyst       75.359878
Data Analyst                 78.349312
Data Scientist               76.332371
Database Administrator       75.243972
DevOps Engineer              77.099193
Frontend Developer           79.969282
Full Stack Developer         75.714894
Java Developer               77.679362
Machine Learning Engineer    76.498166
Product Analyst              77.992671
Project Manager              77.714894
Python Developer             77.688416
QA Engineer                  77.554078
Name: Interview_Score, dtype: float64

In [68]:
print(df['Department'].value_counts())

Department
Software Development     93
Analytics                86
Cloud                    59
AI/ML                    57
Web Development          52
Security                 35
Business Intelligence    33
Database                 27
Testing                  24
Product                  18
Management               16
Name: count, dtype: int64

In [69]:
top_candidates = df.sort_values(
    by = 'Interview_Score',
    ascending=False
)

print(top_candidates.head(10))

    Application_ID      Candidate_Name  Gender  Age         City  \
87         APP0088         Azad Sangha    Male   37    Ahmedabad
254        APP0255      Manikya Sahota    Male   29    Bangalore
11         APP0012      Ryan Ahluwalia  Female   27  Bhubaneswar
285        APP0286        Advika Shere  Female   30      Kolkata
430        APP0431   Divyansh Varghese  Female   35        Noida
207        APP0208           Biju Sama    Male   30        Delhi
65         APP0066  Hrishita Choudhary    Male   34       Mumbai
322        APP0323           Jiya Bath    Male   30       Nagpur
146        APP0147        Purab Cheema    Male   25       Jaipur
109        APP0110         Vidur Koshy  Female   31    Ahmedabad

             State      Qualification          Specialization  \
87         Gujarat               B.E.          Cyber Security
254      Karnataka                MCA            Data Science
11          Odisha  M.Sc Data Science    Software Engineering
285    West Bengal                MBA      Business Analytics
430  Uttar Pradesh             B.Tech        Computer Science
207          Delhi  M.Sc Data Science          Cyber Security
65     Maharashtra             B.Tech      Business Analytics
322    Maharashtra               B.E.  Information Technology
146      Rajasthan                BCA         Cloud Computing
109        Gujarat               B.E.          Cyber Security

                               College_Name  Graduation_Year  ...  \
87                    Arora-Hayre Institute             2021  ...
254       Srinivas, Gour and Dutt Institute             2024  ...
11                   Dass-Sanghvi Institute             2020  ...
285     Khalsa, Sodhi and Khurana Institute             2019  ...
430                     Kanda Ltd Institute             2026  ...
207             Gade, Ram and Ram Institute             2025  ...
65                     Kaur-Uppal Institute             2020  ...
322           Toor, Bumb and Bose Institute             2019  ...
146  Swaminathan, Mani and Aurora Institute             2015  ...
109      Sridhar, Chada and Wable Institute             2023  ...

     Expected_Salary_LPA Current_Salary_LPA Notice_Period_Days  \
87                  25.1               22.7                 45
254                 29.5                0.0                 45
11                   7.0                3.4                 60
285                 13.7                9.4                 30
430                 26.1                0.0                 60
207                 24.9                0.0                 15
65                  17.4               15.9                 90
322                  4.7                2.0                 90
146                 17.1               14.5                 15
109                  5.4                2.6                 90

    Application_Date Interview_Score Technical_Test_Score  \
87        2026-03-02            95.0            78.649351
254       2025-03-21            95.0            66.000000
11        2025-09-06            94.0            65.000000
285       2025-02-19            94.0            89.000000
430       2025-07-19            94.0            88.000000
207       2026-04-21            94.0            64.000000
65        2026-03-18            94.0            78.649351
322       2026-01-13            94.0            78.649351
146       2025-09-19            94.0            77.000000
109       2025-04-30            94.0            63.000000

     Communication_Score    Status  Work_Mode Preferred_Location
87             92.000000   Pending     Remote            Chennai
254            76.992481  Rejected     Remote            Kolkata
11             76.992481  Selected     Hybrid          Hyderabad
285            76.992481  Selected     Onsite          Hyderabad
430            93.000000  Selected     Remote            Chennai
207            76.992481  Rejected     Hybrid              Delhi
65             76.992481  Rejected     Onsite              Delhi
322            76.992481   Pending     Hybrid              Delhi
146            79.000000  Rejected     Onsite              Delhi
109            76.992481  Selected     Hybrid          Hyderabad

[10 rows x 26 columns]

In [70]:
remote = df[
    df['Work_Mode'] == 'Remote'
]

print(remote.head())

   Application_ID      Candidate_Name  Gender  Age         City        State  \
6         APP0007  Ritvik Chakraborty  Female   26       Nagpur  Maharashtra
9         APP0010       Saanvi Kalita  Female   28         Pune  Maharashtra
10        APP0011          Taran Gara    Male   38        Delhi        Delhi
14        APP0015     Vardaniya Madan  Female   24  Bhubaneswar       Odisha
16        APP0017           Urvi Gade    Male   29    Bangalore    Karnataka

        Qualification      Specialization                     College_Name  \
6                 BCA    Computer Science           Sankaran LLC Institute
9   M.Sc Data Science  Business Analytics              Dixit PLC Institute
10             M.Tech             AI & ML      Upadhyay and Sons Institute
14             B.Tech        Data Science  Barad, Manda and Wali Institute
16               B.E.  Business Analytics         Dewan and Sons Institute

    Graduation_Year  ...  Expected_Salary_LPA Current_Salary_LPA  \
6              2024  ...                 31.2                0.0
9              2026  ...                 30.6                0.0
10             2022  ...                 18.5               14.6
14             2023  ...                 26.2               24.2
16             2020  ...                 11.8                7.2

   Notice_Period_Days Application_Date Interview_Score Technical_Test_Score  \
6                  45       2025-03-20            76.0            92.000000
9                  30       2026-01-06            64.0            78.649351
10                 45       2025-04-09            66.0            78.649351
14                 30       2025-01-05            85.0            78.649351
16                 90       2025-06-20            63.0            78.649351

    Communication_Score    Status  Work_Mode Preferred_Location
6                  79.0  Rejected     Remote             Mumbai
9                  73.0  Selected     Remote          Ahmedabad
10                 66.0  Rejected     Remote              Kochi
14                 80.0  Rejected     Remote        Bhubaneswar
16                 62.0  Selected     Remote             Mumbai

[5 rows x 26 columns]

In [71]:
selected = df[df['Status'] == 'Selected']

print(selected.head())

  Application_ID     Candidate_Name  Gender  Age         City           State  \
3        APP0004          Urvi Bora  Female   38      Chennai      Tamil Nadu
5        APP0006       Romil Luthra    Male   24       Indore  Madhya Pradesh
7        APP0008  Kiara Subramanian  Female   38  Bhubaneswar          Odisha
8        APP0009       Anahita Kota    Male   31       Jaipur       Rajasthan
9        APP0010      Saanvi Kalita  Female   28         Pune     Maharashtra

       Qualification      Specialization                 College_Name  \
3               B.E.     Cloud Computing  Banerjee and Sons Institute
5                MBA      Cyber Security       Dubey-Sachar Institute
7               B.E.      Cyber Security     Bhatt-Upadhyay Institute
8             B.Tech        Data Science          Sen-Koshy Institute
9  M.Sc Data Science  Business Analytics          Dixit PLC Institute

   Graduation_Year  ...  Expected_Salary_LPA Current_Salary_LPA  \
3             2023  ...                 10.5                8.4
5             2026  ...                 23.5                0.0
7             2015  ...                 11.4                9.4
8             2017  ...                 16.4               12.7
9             2026  ...                 30.6                0.0

  Notice_Period_Days Application_Date Interview_Score Technical_Test_Score  \
3                 30       2025-07-14       64.000000            94.000000
5                 45       2026-05-13       87.000000            78.649351
7                 60       2025-03-07       65.000000            91.000000
8                 15       2025-04-26       77.429787            78.649351
9                 30       2026-01-06       64.000000            78.649351

   Communication_Score    Status  Work_Mode Preferred_Location
3            76.992481  Selected     Hybrid              Delhi
5            76.992481  Selected     Hybrid              Delhi
7            94.000000  Selected     Onsite             Indore
8            67.000000  Selected     Onsite          Ahmedabad
9            73.000000  Selected     Remote          Ahmedabad

[5 rows x 26 columns]

In [72]:
role_selection = df.groupby(
    'Applied_Role'
)['Status'].value_counts()

print(role_selection)

Applied_Role               Status
AI Engineer                Pending     10
                           Rejected    10
                           Selected     8
BI Developer               Pending     11
                           Rejected     8
                           Selected     5
Backend Developer          Pending     10
                           Selected    10
                           Rejected     6
Business Analyst           Rejected    13
                           Selected    12
                           Pending      8
Cloud Engineer             Pending     13
                           Rejected     9
                           Selected     8
Cyber Security Analyst     Selected    15
                           Pending     13
                           Rejected     7
Data Analyst               Pending     14
                           Rejected    11
                           Selected     9
Data Scientist             Pending     11
                           Selected     9
                           Rejected     8
Database Administrator     Rejected    12
                           Selected     9
                           Pending      6
DevOps Engineer            Rejected    11
                           Selected    11
                           Pending      7
Frontend Developer         Rejected    13
                           Pending     12
                           Selected     7
Full Stack Developer       Selected     8
                           Rejected     7
                           Pending      5
Java Developer             Rejected    15
                           Selected    13
                           Pending     12
Machine Learning Engineer  Selected    12
                           Rejected     9
                           Pending      8
Product Analyst            Pending      9
                           Selected     5
                           Rejected     4
Project Manager            Pending      9
                           Rejected     4
                           Selected     3
Python Developer           Pending     13
                           Rejected     7
                           Selected     7
QA Engineer                Selected     9
                           Pending      8
                           Rejected     7
Name: count, dtype: int64

In [73]:
status_score = df.groupby('Status')[
    ['Interview_Score',
     'Technical_Test_Score',
     'Communication_Score']
].mean()

print(status_score)

          Interview_Score  Technical_Test_Score  Communication_Score
Status
Pending         77.028599             78.601320            77.555005
Rejected        77.882622             79.233202            76.276187
Selected        77.421197             78.352760            77.127538

In [74]:
correlation = df[
    ['Experience_Years',
     'Expected_Salary_LPA',
     'Interview_Score',
     'Technical_Test_Score'
     ]
].corr()

print(correlation)

                      Experience_Years  Expected_Salary_LPA  Interview_Score  \
Experience_Years              1.000000            -0.058857        -0.045069
Expected_Salary_LPA          -0.058857             1.000000         0.011864
Interview_Score              -0.045069             0.011864         1.000000
Technical_Test_Score          0.073466             0.035032        -0.015295

                      Technical_Test_Score
Experience_Years                  0.073466
Expected_Salary_LPA               0.035032
Interview_Score                  -0.015295
Technical_Test_Score              1.000000

In [75]:
# SAVE CLEAN DATASET
df.to_csv("IT_Jobs_cleaned.csv", index=False)