In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("C:/Users/ASUS/Desktop/FBS/Data_Analysis/Data_Set/student_10.csv")

In [3]:
df

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10        2.0        50.0
1  02-07-2021      1002.0     10        6.0        80.0
2  03-07-2021         NaN     10        3.0        60.0
3  06-07-2021         NaN     11        0.0         NaN
4  07-07-2021      1005.0     11        4.0         NaN
5  08-07-2021         NaN     11       10.0         NaN
6  09-07-2021      1007.0     12        4.0        80.0
7  10-07-2021      1008.0     12        NaN        90.0
8  11-07-2021      1009.0     12        NaN        60.0
9  12-07-2021      1010.0     12        6.0        85.0

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Date        10 non-null     str
 1   Student ID  7 non-null      float64
 2   Class       10 non-null     int64
 3   Study hrs   8 non-null      float64
 4   Percentage  7 non-null      float64
dtypes: float64(3), int64(1), str(1)
memory usage: 532.0 bytes

In [6]:
df['Class'] == 12

0    False
1    False
2    False
3    False
4    False
5    False
6     True
7     True
8     True
9     True
Name: Class, dtype: bool

In [7]:
res = df[df['Class'] == 12]
res

         Date  Student ID  Class  Study hrs  Percentage
6  09-07-2021      1007.0     12        4.0        80.0
7  10-07-2021      1008.0     12        NaN        90.0
8  11-07-2021      1009.0     12        NaN        60.0
9  12-07-2021      1010.0     12        6.0        85.0

In [8]:
df['Percentage'] >= 65

0    False
1     True
2    False
3    False
4    False
5    False
6     True
7     True
8    False
9     True
Name: Percentage, dtype: bool

In [10]:
per = df[df['Percentage'] > 75]
per

         Date  Student ID  Class  Study hrs  Percentage
1  02-07-2021      1002.0     10        6.0        80.0
6  09-07-2021      1007.0     12        4.0        80.0
7  10-07-2021      1008.0     12        NaN        90.0
9  12-07-2021      1010.0     12        6.0        85.0

In [11]:
df.head()

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10        2.0        50.0
1  02-07-2021      1002.0     10        6.0        80.0
2  03-07-2021         NaN     10        3.0        60.0
3  06-07-2021         NaN     11        0.0         NaN
4  07-07-2021      1005.0     11        4.0         NaN

In [12]:
df [df['Student ID']  == 1008.0	]

         Date  Student ID  Class  Study hrs  Percentage
7  10-07-2021      1008.0     12        NaN        90.0

In [15]:
df [df['Student ID']  == 1008.0]

         Date  Student ID  Class  Study hrs  Percentage
7  10-07-2021      1008.0     12        NaN        90.0

In [22]:
df.loc[df['Student ID'] ==  1008.0 , 'Percentage'] = 95
df

         Date  Student ID  Class  Study hrs  Percentage
0  01-07-2021      1001.0     10        2.0        50.0
1  02-07-2021      1002.0     10        6.0        80.0
2  03-07-2021         NaN     10        3.0        60.0
3  06-07-2021         NaN     11        0.0         NaN
4  07-07-2021      1005.0     11        4.0         NaN
5  08-07-2021         NaN     11       10.0         NaN
6  09-07-2021      1007.0     12        4.0        80.0
7  10-07-2021      1008.0     12        NaN        95.0
8  11-07-2021      1009.0     12        NaN        60.0
9  12-07-2021      1010.0     12        6.0        85.0

In [33]:
df1 = pd.DataFrame({'id' :[101,102,103], 'Name':['Ishan','Rohit', 'Hardik']})
df1

    id    Name
0  101   Ishan
1  102   Rohit
2  103  Hardik

In [36]:
df2 = pd.DataFrame({'dept_id': [1,2,1], 'dName':['Admin','IT','Admin']})
df2

   dept_id  dName
0        1  Admin
1        2     IT
2        1  Admin

In [38]:
pd.concat([df1,df2], axis = 1)

    id    Name  dept_id  dName
0  101   Ishan        1  Admin
1  102   Rohit        2     IT
2  103  Hardik        1  Admin

In [41]:
pd.concat([df1,df2], axis = 0)

      id    Name  dept_id  dName
0  101.0   Ishan      NaN    NaN
1  102.0   Rohit      NaN    NaN
2  103.0  Hardik      NaN    NaN
0    NaN     NaN      1.0  Admin
1    NaN     NaN      2.0     IT
2    NaN     NaN      1.0  Admin

### Merge

In [42]:
emp = pd.DataFrame({'id' :[101,102,103], 
                    'Name':['Ishan','Rohit', 'Hardik'], 
                    'did': [1,2,3]
                   })
emp

    id    Name  did
0  101   Ishan    1
1  102   Rohit    2
2  103  Hardik    3

In [62]:
dept = pd.DataFrame({'did' :[1,2,3,4,5], 
                     'dName':['IT','Sales', 'HR','Finance', 'Businees']
                    })
dept

   did     dName
0    1        IT
1    2     Sales
2    3        HR
3    4   Finance
4    5  Businees

In [63]:
pd.merge(emp,dept)

    id    Name  did  dName
0  101   Ishan    1     IT
1  102   Rohit    2  Sales
2  103  Hardik    3     HR

In [64]:
pd.merge(emp,dept, how = 'inner')

    id    Name  did  dName
0  101   Ishan    1     IT
1  102   Rohit    2  Sales
2  103  Hardik    3     HR

In [65]:
pd.merge(emp,dept, how = 'outer')

      id    Name  did     dName
0  101.0   Ishan    1        IT
1  102.0   Rohit    2     Sales
2  103.0  Hardik    3        HR
3    NaN     NaN    4   Finance
4    NaN     NaN    5  Businees

In [66]:
pd.merge(emp,dept, how = 'left')

    id    Name  did  dName
0  101   Ishan    1     IT
1  102   Rohit    2  Sales
2  103  Hardik    3     HR

In [67]:
pd.merge(emp,dept, how = 'right')

      id    Name  did     dName
0  101.0   Ishan    1        IT
1  102.0   Rohit    2     Sales
2  103.0  Hardik    3        HR
3    NaN     NaN    4   Finance
4    NaN     NaN    5  Businees